### ISSUE TITLE
circular dependency error

### ISSUE THREAD

**Issue by SOG-web** [better-auth/better-auth#1333]
`Type instantiation is excessively deep and possibly infinite.`

```ts
import { createAuthClient } from "better-auth/react";
import { phoneNumberClient } from "better-auth/client/plugins";
import { rlsClientPlugin } from "./rls-plugin/client";
export const authClient = createAuthClient({
  baseURL: `${process.env.NEXT_PUBLIC_API_ENDPOINT}/auth`,
  plugins: [rlsClientPlugin(), phoneNumberClient()],
});

export const { signIn, signUp, useSession, signOut } = createAuthClient();
```

Am running better-auth on two different nextjs application, I have 100% the same setup, but getting this error on one of the app

please any help would be great thanks

**Comment by ping-maxwell** [comment]
Are you using a monorepo with two next apps within?

**Comment by madisonbullard** [comment]
I'm seeing this as well, running better-auth in a monorepo, but its only used within 1 package in the monorepo currently.

EDIT: My issue ended up being fixed by rolling back `zod` from 3.24.2 to 3.24.1.

I'm not sure this is the case, but I think it might've been a version conflict with the zod version that ships with `better-fetch`

**Comment by SOG-web** [comment]
Have been able to solve it, the error is caused by ts config. I will send the fix in some hours time

**Comment by benjamindell** [comment]
Im also seeing this error. If you're able to share the fix, i'd hugely appreciate it. I'm unable to deploy my code at the moment :(

**Comment by SOG-web** [comment]
> Im also seeing this error. If you're able to share the fix, i'd hugely appreciate it. I'm unable to deploy my code at the moment :(

Try turning on strict in your ts config

**Comment by benjamindell** [comment]
Ah thanks but I already had that set to true. Im still getting the issue - it's grinding my entire project / VScode interface to a halt.

**Comment by SOG-web** [comment]
this is my ts-config

```json
{
  "compilerOptions": {
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "noImplicitAny": false,
    "plugins": [
      {
        "name": "next"
      }
    ],
    "paths": {
      "@/*": ["./src/*"]
    }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
```

**Comment by benjamindell** [comment]
This issue is now entirely resolved for me - the fix for me was upgrading to the 1.2 better-auth beta.
