### ISSUE TITLE
Expo React native node:buffer

### ISSUE THREAD

**Issue by yassinrais** [better-auth/better-auth#1551]
### Is this suited for github?

- [x] Yes, this is suited for github

### To Reproduce

install the latest version of better-auth in an expo react native project

Works fine with `better-auth@1.1.4`

### Current vs. Expected behavior

```
iOS Bundling failed 983ms node_modules/expo-router/entry.js (2434 modules)
The package at "node_modules/jose/dist/node/esm/runtime/base64url.js" attempted to import the Node standard library module "node:buffer".
It failed because the native React runtime does not include the Node standard library.
```

### What version of Better Auth are you using?

^1.1.19

### Provide environment information

```bash
% npm list jose
project@ /Users/abc/acme/project
└─┬ app-mobile@1.0.0 -> ./apps/mobile
  └─┬ better-auth@1.1.19
    └── jose@5.10.0
```

### Which area(s) are affected? (Select all that apply)

Client

### Auth config (if applicable)

```typescript
import { expoClient } from '@better-auth/expo/client';
import {
	emailOTPClient,
	inferAdditionalFields,
	organizationClient,
} from 'better-auth/client/plugins';
import { createAuthClient } from 'better-auth/react';
import { auth } from '../../../../api/src/plugins/auth/better-auth';

import * as SecureStore from 'expo-secure-store';
import { Platform } from 'react-native';

const authClient = createAuthClient({
	baseURL: 'http://localhost:1234/',
	plugins: [
		expoClient({
			scheme: 'test',
			storagePrefix: 'test',
			storage:
				Platform.OS === 'web'
				   ? {
					getItem: window.localStorage.getItem,
					setItem: window.localStorage.setItem,
			              }
				   : SecureStore,
		}),
		organizationClient(),
		inferAdditionalFields<typeof auth>(),
		emailOTPClient(),
	],
});

export default authClient;
```

**Comment by Bekacru** [comment]
should be fixed on `1.1.20-beta.3`

**Comment by yassinrais** [comment]
Thanks! ❤

**Comment by vidhunv1** [comment]
I'm on `^1.1.21` and I get this same error.

This happens only when I use the `anonymous` plugin.

**Comment by irg1008** [comment]
How are you abkle to use window.localstorage when creating the client?

**Comment by jramosg** [comment]
I still have this error with expo 53.0.8 and better-auth 1.2.10

```WARN  Attempted to import the module "/home/jonramos/sandbox/app/TrukunApp/node_modules/@noble/ciphers/crypto.js" which is not listed in the "exports" of "/home/jonramos/sandbox/app/TrukunApp/node_modules/@noble/ciphers" under the requested subpath "./crypto.js". Falling back to file-based resolution. Consider updating the call site or asking the package maintainer(s) to expose this API.
 WARN  Attempted to import the module "/home/jonramos/sandbox/app/TrukunApp/node_modules/@noble/hashes/crypto.js" which is not listed in the "exports" of "/home/jonramos/sandbox/app/TrukunApp/node_modules/@noble/hashes" under the requested subpath "./crypto.js". Falling back to file-based resolution. Consider updating the call site or asking the package maintainer(s) to expose this API.
Android Bundling failed 2512ms node_modules/expo-router/entry.js (2376 modules)
The package at "node_modules/jose/dist/node/esm/runtime/base64url.js" attempted to import the Node standard library module "node:buffer".
It failed because the native React runtime does not include the Node standard library.```

Maybe I'm missing something in metro.config? My metro.config.js is 
```
const { getDefaultConfig } = require("expo/metro-config");

const config = getDefaultConfig(__dirname);

config.resolver.unstable_enablePackageExports = true;

config.resolver.resolveRequest = (context, moduleName, platform) => {
  if (moduleName === "zustand" || moduleName.startsWith("zustand/")) {
    //? Resolve to its CommonJS entry (fallback to main/index.js)
    return {
      type: "sourceFile",
      //? require.resolve will pick up the CJS entry (index.js) since "exports" is bypassed
      filePath: require.resolve(moduleName),
    };
  }

  return context.resolveRequest(context, moduleName, platform);
};

module.exports = config;
````

**Comment by brianwk** [comment]
I'm now getting this error on 1.3.8 of better-auth with Expo / React Native. (Expo SDK 53)

When I downgrade to better-auth and better-auth/expo 1.3.7 the problem no longer persists. 

**Update:** Installing react-native-webcrypto and importing it in the boostrap index.js fixed the issue

**Comment by jancbeck** [comment]
I'm having this issue too. I don't see anything obvious that would cause this though?
https://github.com/better-auth/better-auth/pull/4410/files#diff-a95fa03eaa3ede5409efe90244f6f137c4f09e3354e652b4a4d20500f23c4f40
I'm on SDK 54 preview

**Comment by IronHeartDan** [comment]
+1
