### ISSUE TITLE
Update to 1.3.23 and logging to google leads to state_mismatch

### ISSUE THREAD

**Issue by AceCodePt** [better-auth/better-auth#4969]
### Is this suited for github?

- [x] Yes, this is suited for github

### To Reproduce

I installed the latest version:
    "better-auth": "^1.3.23",

from  1.3.12

I'm trying to have a link to social in astro and have the login from astro.
After logging I'm getting the following screen:

<img width="1642" height="888" alt="Image" src="https://github.com/user-attachments/assets/a34ff9f2-3ed6-4fe7-a31c-ef938ae7bac6" />

### Current vs. Expected behavior

It should just work...
But it doesn't

### What version of Better Auth are you using?

1.3.23

### System info

```bash
{
  "system": {
    "platform": "linux",
    "arch": "x64",
    "version": "#78-Ubuntu SMP PREEMPT_DYNAMIC Tue Aug 12 11:34:18 UTC 2025",
    "release": "6.8.0-78-generic",
    "cpuCount": 20,
    "cpuModel": "12th Gen Intel(R) Core(TM) i7-12700H",
    "totalMemory": "62.50 GB",
    "freeMemory": "55.29 GB"
  },
  "node": {
    "version": "v24.6.0",
    "env": "development"
  },
  "packageManager": {
    "name": "pnpm",
    "version": "10.17.1"
  },
  "frameworks": [
    {
      "name": "astro",
      "version": "^5.14.1"
    }
  ],
  "databases": [
    {
      "name": "postgres",
      "version": "^3.4.7"
    }
  ],
  "betterAuth": {
    "version": "^1.3.23",
    "config": {
      "socialProviders": {
        "google": {
          "clientId": "[REDACTED]",
          "clientSecret": "[REDACTED]",
          "enabled": true
        }
      },
      "database": {
        "dialect": {},
        "type": "postgres"
      },
      "user": {
        "fields": {
          "emailVerified": "email_verified",
          "createdAt": "created_at",
          "updatedAt": "updated_at"
        }
      },
      "session": {
        "fields": {
          "userId": "user_id",
          "expiresAt": "expires_at",
          "createdAt": "created_at",
          "updatedAt": "updated_at",
          "ipAddress": "ip_address",
          "userAgent": "user_agent"
        }
      },
      "account": {
        "fields": {
          "userId": "user_id",
          "accountId": "account_id",
          "providerId": "provider_id",
          "accessToken": "[REDACTED]",
          "refreshToken": "[REDACTED]",
          "idToken": "[REDACTED]",
          "accessTokenExpiresAt": "access_token_expires_at",
          "refreshTokenExpiresAt": "refresh_token_expires_at",
          "createdAt": "created_at",
          "updatedAt": "updated_at"
        }
      },
      "verification": {
        "fields": {
          "expiresAt": "expires_at",
          "createdAt": "created_at",
          "updatedAt": "updated_at"
        }
      }
    }
  }
}
```

### Which area(s) are affected? (Select all that apply)

Backend

### Auth config (if applicable)

```typescript
import { betterAuth } from "better-auth";
import sql from "./sql";
import { PostgresJSDialect } from "kysely-postgres-js";

export const auth = betterAuth({
  socialProviders: {
    google: {
      clientId: process.env?.GOOGLE_CLIENT_ID!,
      clientSecret: process.env?.GOOGLE_CLIENT_SECRET!,
      enabled: true,
    },
  },
  database: {
    dialect: new PostgresJSDialect({
      postgres: sql,
    }),
    type: "postgres",
  },
  user: {
    fields: {
      emailVerified: "email_verified",
      createdAt: "created_at",
      updatedAt: "updated_at",
    },
  },
  session: {
    fields: {
      userId: "user_id",
      expiresAt: "expires_at",
      createdAt: "created_at",
      updatedAt: "updated_at",
      ipAddress: "ip_address",
      userAgent: "user_agent",
    },
  },
  account: {
    fields: {
      userId: "user_id",
      accountId: "account_id",
      providerId: "provider_id",
      accessToken: "access_token",
      refreshToken: "refresh_token",
      idToken: "id_token",
      accessTokenExpiresAt: "access_token_expires_at",
      refreshTokenExpiresAt: "refresh_token_expires_at",
      createdAt: "created_at",
      updatedAt: "updated_at",
    },
  },
  verification: {
    fields: {
      expiresAt: "expires_at",
      createdAt: "created_at",
      updatedAt: "updated_at",
    },
  },
});
```

### Additional context

Multiple changes where made:
first the sql: 

```ts
const sql = postgres({
  connection: {
    search_path: "public, auth",
  },
...
})
```

All my tables are in `auth schema`

I also made modifications to the middleware to support the use of htmx:
```ts
import logger from "@/lib/logger";
import safeAsync from "@/lib/util/safeAsync";
import { auth } from "@auth";
import type { APIRoute } from "astro";
import { z } from "astro/zod";

export const ALL: APIRoute = async (ctx) => {
  // ctx.request.headers.set("x-forwarded-for", ctx.clientAddress);
  const response = await safeAsync(auth.handler(ctx.request));

  if (response.error) {
    logger.error(`Something didn't work with better auth`, response.error);
    return new Response("Unexpected error occured", { status: 500 });
  }

  if (ctx.url.pathname === "/api/auth/sign-in/social") {
    const rawBodyResponse = await safeAsync(response.data.json());
    if (rawBodyResponse.error) {
      logger.error(`Couldn't parse raw response as json`, response.error);
      return new Response("Unexpected error occured", { status: 500 });
    }

    const expectedBody = z
      .object({ url: z.string().url() })
      .safeParse(rawBodyResponse.data);

    if (expectedBody.error) {
      logger.error(
        `The body received from better auth was malformed`,
        response.error,
      );
      return new Response("Unexpected error occured", { status: 500 });
    }

    return new Response("", {
      headers: { "HX-Redirect": expectedBody.data.url },
    });
  }

  console.log(ctx.url, response.data);

  return response.data;
};

```

**Comment by AceCodePt** [comment]
1. Checked.
2. Made the modifications (didn't help)
3. I see in the logs the cookies.
4. I only provided a provider of google with a single client_id
5. I'm using a kysely adapter so I highly doubt that that is an issue.

**Comment by Bekacru** [comment]
You should set cookies on the client for `state`. We had a weird workaround in the previous versions that's no longer supported. The way you're using the api here is a bit weird. I suggest using `authClient` directly

**Comment by AceCodePt** [comment]
Isn't there a way for a more server side solution?

**Comment by Dougsworth** [comment]
hi were you able to resolve this?

**Comment by rohovskoi** [comment]
@Bekacru Hey 👋

Are there any other endpoints affected except for social and SSO auth? 

I implemented everything on my server and on my client I call my custom server endpoints (I don't use `createAuthClient()`) at all. 

Do you plan for other endpoints the same? This would be painful to migrate..

**Comment by Bekacru** [comment]
Hey, only oauth (social,sso,generic oauth) endpoints are affected

**Comment by Balance8** [comment]
is this fixed? I am still running into it with github

**Comment by danbarbarito** [comment]
I'm still seeing this too. Downgrading to version 1.2.12 works for now..

**Comment by jjjrmy** [comment]
the last version working for me is `1.3.18`, if I upgrade past that then I get `state_mismatch`

**Comment by AceCodePt** [comment]
@Bekacru The issue still persist. Further more if is possible I would like a server side solution.
While I can create my own endpoint to call the auth endpoint I'm curious for why not call the better-auth endpoint itself.

**Comment by Fruup** [comment]
@Bekacru What exactly do you mean by "You should set cookies on the client for `state`"? I can't find any documentation on this, unfortunately. I'm using the `authClient` from the SDK.

---

## Edit:

~~I found out that the `authClient` sets this cookie automatically. My issue is that I'm trying to authenticate from domain `a.com` while better-auth is running at domain another domain `b.com`. The cookies will only be available at domain `b.com`.~~

~~Is there a way to achieve cross-domain authentication using SSO, or is this out of scope for this library?~~

I found out this is possible by setting the following:

```ts
betterAuth({
  ...,
  advanced: {
    defaultCookieAttributes: {
      sameSite: 'None', // this enables cross-site cookies
      secure: true, // required for SameSite=None
    },
  }
})
```

This is exactly what I wanted :) The `trustedOrigins` option is also respected, so I don't see a huge security implication here.

**Comment by abhijitxy** [comment]
downgraded and it's working now

**Comment by jdtzmn** [comment]
@abhijitxy to what version?

**Comment by abhijitxy** [comment]
> [@abhijitxy](https://github.com/abhijitxy) to what version?

1.2.12

**Comment by martinriviere** [comment]
Hi! Aren't there still no solutions to perform an OAuth sign in on the server?
The OAuth generic plugin [documentation](https://www.better-auth.com/docs/plugins/generic-oauth#api-method-sign-in-oauth2) still shows that possibility, but it seems it can't be done?
The `signInWithOAuth2` api method returns an url that we can we can use to redirect request, but still get a `state_mismatch` error after sign in 😕 
Downgrading and using authClient is unfortunately not an option in one of my cases, where we have no control over client and is 100% SSR...

**Comment by JoshuaSmeda** [comment]
I'm getting the same error on version `1.3.32`

**Comment by geekyharsh05** [comment]
@Bekacru I am getting the same error on Version `1.3.34,` only **OAuth** is not working, Signin with creds is working (email, pass).

**Comment by letstri** [comment]
For now you can use temp solution to disable state mismatch with this plugin:

```
export function skipStateMismatch(): BetterAuthPlugin {
  return {
    id: 'skip-state-mismatch',
    init(ctx) {
      return {
        context: {
          ...ctx,
          oauthConfig: {
            skipStateCookieCheck: true,
            ...ctx?.oauthConfig,
          },
        },
      }
    },
  }
}
```

**Comment by thatanjan** [comment]
I'm getting the same error.
Downgraded to v1.2.12 and it is working.
My code:
```javascript
export async function signInWithGoogle() {
  const result = await auth.api.signInSocial({
    body: {
      provider: "google",
      callbackURL: "/", // Redirect here after successful Google login
    },
  });
```
