### ISSUE TITLE
Regression due to changed types in admin plugin hooks

### ISSUE THREAD

**Issue by ChristianIvicevic** [better-auth/better-auth#5674]
### Is this suited for github?

- [x] Yes, this is suited for github

### To Reproduce

Reproduction repository: https://github.com/ChristianIvicevic/better-auth-headers-repro

Open the `src/index.ts` file and notice how `admin()` cannot be passed to the `plugins` array without a type error due to possibly undefined headers in the hooks, which hasn't been the case before.

This is a regression since 1.3.28, the previous version 1.3.27 does NOT have the same issue.

### Current vs. Expected behavior

Currently, throwing the following type error:
```
Type '{ id: "admin"; init(): { options: { databaseHooks: { user: { create: { before(user: { id: string; createdAt: Date; updatedAt: Date; email: string; emailVerified: boolean; name: string; image?: string | ... 1 more ... | undefined; } & Record<...>): Promise<...>; }; }; session: { ...; }; }; }; }; ... 4 more ...; optio...' is not assignable to type 'BetterAuthPlugin'.
  The types of 'hooks.after' are incompatible between these types.
    Type '{ matcher(context: EndpointContext<string, any> & Omit<InputContext<string, any>, "method"> & { context: AuthContext & { returned?: unknown; responseHeaders?: Headers; }; headers?: Headers; }): boolean; handler: (inputContext: MiddlewareInputContext<...>) => Promise<...>; }[]' is not assignable to type '{ matcher: (context: HookEndpointContext) => boolean; handler: (inputContext: MiddlewareInputContext<MiddlewareOptions>) => Promise<...>; }[]'.
      Type '{ matcher(context: EndpointContext<string, any> & Omit<InputContext<string, any>, "method"> & { context: AuthContext & { returned?: unknown; responseHeaders?: Headers; }; headers?: Headers; }): boolean; handler: (inputContext: MiddlewareInputContext<...>) => Promise<...>; }' is not assignable to type '{ matcher: (context: HookEndpointContext) => boolean; handler: (inputContext: MiddlewareInputContext<MiddlewareOptions>) => Promise<...>; }'.
        Types of property 'matcher' are incompatible.
          Type '(context: EndpointContext<string, any> & Omit<InputContext<string, any>, "method"> & { context: AuthContext & { returned?: unknown; responseHeaders?: Headers; }; headers?: Headers; }) => boolean' is not assignable to type '(context: HookEndpointContext) => boolean'.
            Types of parameters 'context' and 'context' are incompatible.
              Type 'HookEndpointContext' is not assignable to type 'EndpointContext<string, any> & Omit<InputContext<string, any>, "method"> & { context: AuthContext & { returned?: unknown; responseHeaders?: Headers; }; headers?: Headers; }' with 'exactOptionalPropertyTypes: true'. Consider adding 'undefined' to the types of the target's properties.
                Type 'HookEndpointContext' is not assignable to type '{ context: AuthContext & { returned?: unknown; responseHeaders?: Headers; }; headers?: Headers; }' with 'exactOptionalPropertyTypes: true'. Consider adding 'undefined' to the types of the target's properties.
                  Types of property 'headers' are incompatible.
                    Type '(Headers & HeadersInit) | undefined' is not assignable to type 'Headers'.
                      Type 'undefined' is not assignable to type 'Headers'.ts(2322)
```

### What version of Better Auth are you using?

1.3.28

### System info

```bash
{
  "system": {
    "platform": "darwin",
    "arch": "arm64",
    "version": "Darwin Kernel Version 24.6.0: Mon Jul 14 11:30:55 PDT 2025; root:xnu-11417.140.69~1/RELEASE_ARM64_T6031",
    "release": "24.6.0",
    "cpuCount": 16,
    "cpuModel": "Apple M3 Max",
    "totalMemory": "48.00 GB",
    "freeMemory": "3.33 GB"
  },
  "node": {
    "version": "v22.20.0",
    "env": "development"
  },
  "packageManager": {
    "name": "npm",
    "version": "10.9.3"
  },
  "frameworks": null,
  "databases": null,
  "betterAuth": {
    "version": "1.3.28",
    "config": null
  }
}
```

### Which area(s) are affected? (Select all that apply)

Backend

### Auth config (if applicable)

```typescript
import { betterAuth } from 'better-auth'
import { admin } from 'better-auth/plugins'

const auth = betterAuth({ plugins: [admin()] })
```

**Comment by ping-maxwell** [comment]
can you share your tsconfig?

**Comment by ping-maxwell** [comment]
oh, got it:
```json
{
	"compilerOptions": {
		"disableSourceOfProjectReferenceRedirect": true,
        "allowJs": false,
		"checkJs": false,
		"composite": true,
		"declaration": true,
		"declarationMap": true,
		"downlevelIteration": true,
		"emitDecoratorMetadata": true,
		"esModuleInterop": false,
		"exactOptionalPropertyTypes": true,
		"experimentalDecorators": true,
		"forceConsistentCasingInFileNames": true,
		"module": "Preserve",
		"moduleDetection": "force",
		"moduleResolution": "bundler",
		"noEmitOnError": false,
		"noErrorTruncation": false,
		"noFallthroughCasesInSwitch": true,
		"noImplicitAny": true,
		"noImplicitReturns": false,
		"noImplicitThis": true,
		"noUncheckedIndexedAccess": true,
		"noUnusedLocals": true,
		"noUnusedParameters": false,
		"removeComments": false,
		"sourceMap": true,
		"strictNullChecks": true,
		"target": "ES2023",
		"baseUrl": "./src",
		"incremental": true,
		"isolatedModules": true,
		"lib": ["ES2022", "ES2023", "DOM", "DOM.Iterable"],
		"noEmit": true,
		"outDir": "dist",
		"resolveJsonModule": true,
		"rootDir": ".",
		"skipLibCheck": true,
		"strict": true,
		"tsBuildInfoFile": ".tsbuildinfo/src.tsbuildinfo"
	},
	"exclude": ["node_modules"],
	"include": ["src", "test"]
}
```

**Comment by ping-maxwell** [comment]
Better-auth tends to break when `declaration`, `declarationMap`, `exactOptionalPropertyTypes` are enabled.
Although I believe some of our team members have worked on improving this if not resolves these already..

cc @himself65

**Comment by ChristianIvicevic** [comment]
I can confirm that `exactOptionalPropertyTypes` is the cause of the regression, but you can imagine that reducing strictness is not a maintainable long-term solution.

**Comment by ChristianIvicevic** [comment]
A **temporary** fix for this is the use of `type-fest` such as this:
```ts
import { betterAuth } from 'better-auth'
import { admin } from 'better-auth/plugins'
import type { UndefinedOnPartialDeep } from 'type-fest'

const auth = betterAuth({
	plugins: [admin() as UndefinedOnPartialDeep<ReturnType<typeof admin>>],
})
```
This is an escape hatch and should not be necessary long-term.

**Comment by lensbart** [comment]
Same for `apiKey` plugin

**Comment by himself65** [comment]
I beliebe we have fixed this in 1.4

**Comment by ChristianIvicevic** [comment]
> I beliebe we have fixed this in 1.4

I tried out 1.4 and it seems to be fixed for the `admin` plugin specifically, but there is another regression due to types not being able to be named without a reference mentioned in #5574 and most notably the comment here: https://github.com/better-auth/better-auth/issues/5574#issuecomment-3456341626

For as long as that other bug is not fixed and 1.4 is not marked as stable, users have to stay on 1.3.27 for now.

**Comment by himself65** [comment]
We have fixed this in 1.3, latest I believe? and also be fixed in 1.4 beta

**Comment by ChristianIvicevic** [comment]
> We have fixed this in 1.3, latest I believe? and also be fixed in 1.4 beta

No, this is not fixed in 1.3.34.
Only in 1.4 which itself is not yet stable and has other regressions.
