### ISSUE TITLE
better-auth@1.4.7 is conflict with prisma@7.2.0

### ISSUE THREAD

**Issue by Chavda2772** [better-auth/better-auth#6923]
### Is this suited for github?

- [ ] Yes, this is suited for github

### To Reproduce

Steps to recreate this issue.
1. Install prisma@latest (7.2.0).
2. Try to install better-auth@latest (1.4.7)

Not able to install better-auth it throw an error
==========================================
E:\WebApplication\Github\Settlr>**npm install better-auth@latest**
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: settlr@0.1.0
npm error Found: prisma@7.2.0
npm error node_modules/prisma
npm error   dev prisma@"^7.2.0" from the root project
npm error   peerOptional prisma@"*" from @prisma/client@7.2.0
npm error   node_modules/@prisma/client
npm error     @prisma/client@"^7.2.0" from the root project
npm error     peerOptional @prisma/client@"*" from drizzle-orm@0.41.0
npm error     node_modules/drizzle-orm
npm error       peerOptional drizzle-orm@"^0.41.0" from better-auth@1.4.7
npm error       node_modules/better-auth
npm error         better-auth@"1.4.7" from the root project
npm error
npm error Could not resolve dependency:
npm error peerOptional prisma@"^5.22.0" from better-auth@1.4.7
npm error node_modules/better-auth
npm error   better-auth@"1.4.7" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.

### Current vs. Expected behavior

Currently it throw an error.

### What version of Better Auth are you using?

1.4.7

### System info

```bash
1.4.7
```

### Which area(s) are affected? (Select all that apply)

Package

### Auth config (if applicable)

```typescript
import { betterAuth } from "better-auth"
export const auth = betterAuth({
  emailAndPassword: {  
    enabled: true
  },
});
```

**Comment by tavongamatikiti** [comment]
You can try v1.4.8-beta.1 and it is fixed in https://github.com/better-auth/better-auth/commit/00ede9037a4bce5f48f9adc0bc01d6e34056af3c

**Comment by RockyAiii** [comment]
Just want to tag in that i upgraded to prisma 7.2.0 earlier on . Everything was sweet with better-auth 1.4.5 and prisma 7.1.0 though a few niggles still going with prisma but could log in all fine. Soon as i went to 7.2.0, could not log in at all. Went to upgrade better-auth and ran into the same issue as above. I've just tried 1.4.8-beta-1 which installed fine but still can't log in. I get a log of these errors Error: sourceMapURL could not be parsed.

**Comment by himself65** [comment]
You can try v1.4.8-beta.1 and it is fixed in https://github.com/better-auth/better-auth/commit/00ede9037a4bce5f48f9adc0bc01d6e34056af3c

Closing

**Comment by Chavda2772** [comment]
Hi @RockyAiii ,
Better-auth@1.4.5 and 
Prisma@7.1.0

works for me.
@himself65 
Once better-auth@1.4.8 release I will upgrade.

Thank you 
@RockyAiii and @himself65
