### ISSUE TITLE
better-auth expo plugin expo-origin header bypass takes no effect because of setting readonly request headers

### ISSUE THREAD

**Issue by techzealot** [better-auth/better-auth#7014]
### Is this suited for github?

- [ ] Yes, this is suited for github

### To Reproduce

1. use regular better-auth expo config and use emailAndPassword plugin
2. config your trustedOrigins such as "my-app://"
3. call signIn or any other api
4. MISSING_OR_NULL_ORIGIN error occurred

### Current vs. Expected behavior

current:
expo-origin header override failed to  add  origin, thus cause MISSING_OR_NULL_ORIGIN error

expected:
the expo plugin add correct origin to avoid origin check error

### What version of Better Auth are you using?

1.4.7

### System info

```bash
1. macos
2. node v23.10.0
3. better-auth 1.4.6
4. expo 53.0.24
```

### Which area(s) are affected? (Select all that apply)

Package

### Auth config (if applicable)

```typescript
const options = {
  experimental: {
    joins: true
  },
  database: drizzleAdapter(db, {
    provider: "pg"
  }),
  
  baseURL: CONFIG.BETTER_AUTH_URL,

  emailAndPassword: {
    enabled: true,
    requireEmailVerification: false,
  },
  plugins: [
    expo(),
    admin(),
 ],

  trustedOrigins: [
    "http://localhost:3000",
    "http://localhost:8081", // Expo dev server
    "my-app://", // Expo app scheme
    "exp://", // Expo Go
  ]
} satisfies BetterAuthOptions;
```

### Additional context

I think the header bypass logic caused the problem:

https://github.com/better-auth/better-auth/blob/9c54c108db80c5e51e824242416b3f2554331b10/packages/expo/src/index.ts#L26-L43

the request.headers is readonly ,set takes no effect

I write a fix plugin to test the correct solution, it works:
```
export const expoOriginFix = (): BetterAuthPlugin => {
  return {
    id: "expo-origin-fix",
    onRequest: async (request) => {
     
      const expoOrigin = request.headers.get("expo-origin");

      if (!expoOrigin) {
       
        return;
      }

      // create new header because request.headers is readonly 
      const newHeaders = new Headers(request.headers);
      newHeaders.set("origin", expoOrigin)

      const newRequest = new Request(request, {
        headers: newHeaders
      });

      return {
        request: newRequest,
      };
    },
  };
};

```

**Comment by bytaesu** [comment]
<img width="818" height="126" alt="Image" src="https://github.com/user-attachments/assets/4f734948-9136-4072-86c9-2340248c0acb" />

Hi @techzealot,

As I understand it, the read-only headers property prevents reassigning the Headers object itself, but does not prevent using its methods. When I set up an Expo app myself by following the guide, I didn't run into this issue. Could you let me know which environment this happens in, or share a reproducible minimal repo?


---

Also, there was an issue with trustedOrigins in the recent `1.4.x` patches, which was fixed in `1.4.9`. I didn't see this issue when testing with `1.4.7`, but could you check whether it still occurs on the latest version? It's possible this is related to that fix.

- https://github.com/better-auth/better-auth/pull/6887

**Comment by techzealot** [comment]
@bytaesu I tested the v1.4.9 version, the error still remains.
this is the minimal repo:
https://github.com/techzealot/better-auth-expo-origin-case

an expo client and a hono backend, and if you uncomment the test plugin "expoOriginFix" ,the error will disappear.
this shows we add header in the wrong way.
but I found another problem, if we use the expo plugin, any other following plugin's onRequest will not execute, I guess the onRequest chain is  short-circuit once we return a new request.I think this is not good as the expo plugin occupy the only chance to use the onRequest.

**Comment by bytaesu** [comment]
Hi @techzealot,

After testing, `request.clone()` itself works fine.

In your case, this issue happens because `@hono/node-server` uses a pseudo Request object. Because of that, I found an edge case in how `better-call` (used internally by `better-auth`) handles Request, and I will fix it.

Also your point about the onRequest chain makes sense, and I'll fix that as well.

Thanks for providing the example repo. It really helped me identify the issue 🙏

**Comment by focux** [comment]
Just a heads up, I tested it with the new version of `better-call` and the issue still persists. Using `hono` on the backend as well.

**Comment by bytaesu** [comment]
@focux thanks for letting me know 🙏


I’ll check what’s missing

**Comment by bytaesu** [comment]
> Just a heads up, I tested it with the new version of `better-call` and the issue still persists. Using `hono` on the backend as well.

Are you using v1.4.11 ??

**Comment by focux** [comment]
@bytaesu  I'm using `1.5.0-beta.3` which I'm pretty sure have the fix but I might be wrong hah.

**Comment by bytaesu** [comment]
@focux  Ok just for checking!

I will look into this, no worries 😄

**Comment by bytaesu** [comment]
> [@bytaesu](https://github.com/bytaesu) I'm using `1.5.0-beta.3` which I'm pretty sure have the fix but I might be wrong hah.

I checked, and this PR seems to have been missed in the following release.. I’ve shared this with the team 🙏

**Comment by focux** [comment]
I tested again with `v1.4.18` and still not working. I'm using Hono and still getting the: `Can't modify immutable headers problem`.

Also, I ran `pnpm why better-call` to know what version of `better-call` it was using and seems to be using `v1.1.8` which is the one who's supposed to have the fix.

**Edit**
This is the workaround for now https://github.com/better-auth/better-auth/issues/5568#issuecomment-3617470030

**Comment by bytaesu** [comment]
Hi @focux,

While building and testing an Expo app myself, I realized this issue still occurs in environments like Cloudflare Workers. I’ve applied a fix, and it will be included in the next release 🙏

**Comment by focux** [comment]
@bytaesu Thank you so much! I'm looking forward to try the fix 🙏🏼
